# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='train.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btrain.proto\"\xb9\x01\n\x05Train\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tmaterials\x18\x02 \x03(\t\x12\x33\n\x0fpassagire_count\x18\x03 \x03(\x0b\x32\x1a.Train.PassagireCountEntry\x12\x13\n\x0bwagon_count\x18\x04 \x01(\x05\x12\x0e\n\x06length\x18\x05 \x01(\x02\x1a\x35\n\x13PassagireCountEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3'
)




_TRAIN_PASSAGIRECOUNTENTRY = _descriptor.Descriptor(
  name='PassagireCountEntry',
  full_name='Train.PassagireCountEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Train.PassagireCountEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Train.PassagireCountEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=201,
)

_TRAIN = _descriptor.Descriptor(
  name='Train',
  full_name='Train',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Train.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='materials', full_name='Train.materials', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passagire_count', full_name='Train.passagire_count', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wagon_count', full_name='Train.wagon_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='Train.length', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TRAIN_PASSAGIRECOUNTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=201,
)

_TRAIN_PASSAGIRECOUNTENTRY.containing_type = _TRAIN
_TRAIN.fields_by_name['passagire_count'].message_type = _TRAIN_PASSAGIRECOUNTENTRY
DESCRIPTOR.message_types_by_name['Train'] = _TRAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Train = _reflection.GeneratedProtocolMessageType('Train', (_message.Message,), {

  'PassagireCountEntry' : _reflection.GeneratedProtocolMessageType('PassagireCountEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRAIN_PASSAGIRECOUNTENTRY,
    '__module__' : 'train_pb2'
    # @@protoc_insertion_point(class_scope:Train.PassagireCountEntry)
    })
  ,
  'DESCRIPTOR' : _TRAIN,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:Train)
  })
_sym_db.RegisterMessage(Train)
_sym_db.RegisterMessage(Train.PassagireCountEntry)


_TRAIN_PASSAGIRECOUNTENTRY._options = None
# @@protoc_insertion_point(module_scope)
